# Generated by Django 6.0.7 on 2026-07-28 21:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllWardsMathare',
            fields=[
                ('fid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.BigIntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('layer', models.CharField(blank=True, max_length=254, null=True)),
                ('path', models.CharField(blank=True, max_length=254, null=True)),
                ('mathare_ufn_village', models.CharField(blank=True, max_length=255, null=True)),
                ('mathare_ufn_ufn_equal', models.FloatField(blank=True, null=True)),
                ('mathare_ufn_ufn_interim_weighted', models.FloatField(blank=True, null=True)),
                ('mathare_ufn_q_1d', models.FloatField(blank=True, null=True)),
                ('mathare_ufn_upstream_area_km2_local', models.FloatField(blank=True, null=True)),
                ('mathare_ufn_usi', models.FloatField(blank=True, null=True)),
                ('mathare_ufn_dsi_proxy', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_wards_mathare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('ward_fid', models.BigIntegerField(blank=True, null=True)),
                ('ward_name', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'phone_users',
            },
        ),
    ]
