# Generated by Django 6.0.7 on 2026-07-29 09:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoisJoined',
            fields=[
                ('id_0', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.BigIntegerField(blank=True, null=True)),
                ('id', models.CharField(blank=True, max_length=100, null=True)),
                ('grid_id', models.IntegerField(blank=True, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('village_match', models.TextField(blank=True, null=True)),
                ('mathare_ufn_village', models.CharField(blank=True, max_length=255, null=True)),
                ('mathare_ufn_ufn_equal', models.FloatField(blank=True, db_column='mathare_ufn_UFN_equal', null=True)),
                ('mathare_ufn_ufn_interim_weighted', models.FloatField(blank=True, db_column='mathare_ufn_UFN_interim_weighted', null=True)),
                ('mathare_ufn_q_1d', models.FloatField(blank=True, db_column='mathare_ufn_Q_1d', null=True)),
                ('mathare_ufn_upstream_area_km2_local', models.FloatField(blank=True, null=True)),
                ('mathare_ufn_usi', models.FloatField(blank=True, db_column='mathare_ufn_USI', null=True)),
                ('mathare_ufn_dsi_proxy', models.FloatField(blank=True, db_column='mathare_ufn_DSI_proxy', null=True)),
                ('fid_2', models.BigIntegerField(blank=True, null=True)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pois_joined',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoadsJoined',
            fields=[
                ('id_0', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.BigIntegerField(blank=True, null=True)),
                ('id', models.CharField(blank=True, max_length=100, null=True)),
                ('grid_id', models.IntegerField(blank=True, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('village_match', models.TextField(blank=True, null=True)),
                ('mathare_ufn_village', models.CharField(blank=True, max_length=255, null=True)),
                ('mathare_ufn_ufn_equal', models.FloatField(blank=True, db_column='mathare_ufn_UFN_equal', null=True)),
                ('mathare_ufn_ufn_interim_weighted', models.FloatField(blank=True, db_column='mathare_ufn_UFN_interim_weighted', null=True)),
                ('mathare_ufn_q_1d', models.FloatField(blank=True, db_column='mathare_ufn_Q_1d', null=True)),
                ('mathare_ufn_upstream_area_km2_local', models.FloatField(blank=True, null=True)),
                ('mathare_ufn_usi', models.FloatField(blank=True, db_column='mathare_ufn_USI', null=True)),
                ('mathare_ufn_dsi_proxy', models.FloatField(blank=True, db_column='mathare_ufn_DSI_proxy', null=True)),
                ('fid_2', models.BigIntegerField(blank=True, null=True)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.CharField(blank=True, max_length=20, null=True)),
                ('oneway', models.CharField(blank=True, max_length=1, null=True)),
                ('maxspeed', models.IntegerField(blank=True, null=True)),
                ('layer', models.IntegerField(blank=True, null=True)),
                ('bridge', models.CharField(blank=True, max_length=1, null=True)),
                ('tunnel', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'roads_joined',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterwaysJoined',
            fields=[
                ('id_0', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.BigIntegerField(blank=True, null=True)),
                ('id', models.CharField(blank=True, max_length=100, null=True)),
                ('grid_id', models.IntegerField(blank=True, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('village_match', models.TextField(blank=True, null=True)),
                ('mathare_ufn_village', models.CharField(blank=True, max_length=255, null=True)),
                ('mathare_ufn_ufn_equal', models.FloatField(blank=True, db_column='mathare_ufn_UFN_equal', null=True)),
                ('mathare_ufn_ufn_interim_weighted', models.FloatField(blank=True, db_column='mathare_ufn_UFN_interim_weighted', null=True)),
                ('mathare_ufn_q_1d', models.FloatField(blank=True, db_column='mathare_ufn_Q_1d', null=True)),
                ('mathare_ufn_upstream_area_km2_local', models.FloatField(blank=True, null=True)),
                ('mathare_ufn_usi', models.FloatField(blank=True, db_column='mathare_ufn_USI', null=True)),
                ('mathare_ufn_dsi_proxy', models.FloatField(blank=True, db_column='mathare_ufn_DSI_proxy', null=True)),
                ('fid_2', models.BigIntegerField(blank=True, null=True)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'waterways_joined',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='phoneuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili'), ('sheng', 'Sheng')], default='en', max_length=10),
        ),
    ]
