# Generated by Django 6.0.7 on 2026-07-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_pofw'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('blocked_drainage', 'Blocked drainage'), ('drainage_expansion', 'Drainage expansion needed'), ('broken_water_point', 'Broken/contaminated water point'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('reported', 'Reported (unverified)'), ('verified', 'Verified'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected (false report / not actionable)')], default='reported', max_length=20)),
                ('ward_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ward_fid', models.BigIntegerField(blank=True, null=True)),
                ('reported_by_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'maintenance_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
